
package br.edu.ifpb.pos.passagem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServicePassagemService", targetNamespace = "http://passagem.pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/ServicePassagemService/ServicePassagem?WSDL")
public class ServicePassagemService
    extends Service
{

    private final static URL SERVICEPASSAGEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEPASSAGEMSERVICE_EXCEPTION;
    private final static QName SERVICEPASSAGEMSERVICE_QNAME = new QName("http://passagem.pos.ifpb.edu.br/", "ServicePassagemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicePassagemService/ServicePassagem?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEPASSAGEMSERVICE_WSDL_LOCATION = url;
        SERVICEPASSAGEMSERVICE_EXCEPTION = e;
    }

    public ServicePassagemService() {
        super(__getWsdlLocation(), SERVICEPASSAGEMSERVICE_QNAME);
    }

    public ServicePassagemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServicePassagem
     */
    @WebEndpoint(name = "ServicePassagemPort")
    public ServicePassagem getServicePassagemPort() {
        return super.getPort(new QName("http://passagem.pos.ifpb.edu.br/", "ServicePassagemPort"), ServicePassagem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePassagem
     */
    @WebEndpoint(name = "ServicePassagemPort")
    public ServicePassagem getServicePassagemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://passagem.pos.ifpb.edu.br/", "ServicePassagemPort"), ServicePassagem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEPASSAGEMSERVICE_EXCEPTION!= null) {
            throw SERVICEPASSAGEMSERVICE_EXCEPTION;
        }
        return SERVICEPASSAGEMSERVICE_WSDL_LOCATION;
    }

}
