package chat;


/**
* chat/Chat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatCorba.idl
* Quinta-feira, 22 de Junho de 2017 11h00min27s GFT
*/

public interface Chat extends ChatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chat
