
package br.edu.ifpb.pos.biblioteca;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BibliotecaService", targetNamespace = "http://atividade4.server.soap.pos.pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-server-atividade4/BibliotecaService?wsdl")
public class BibliotecaService
    extends Service
{

    private final static URL BIBLIOTECASERVICE_WSDL_LOCATION;
    private final static WebServiceException BIBLIOTECASERVICE_EXCEPTION;
    private final static QName BIBLIOTECASERVICE_QNAME = new QName("http://atividade4.server.soap.pos.pos.ifpb.edu.br/", "BibliotecaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-server-atividade4/BibliotecaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOTECASERVICE_WSDL_LOCATION = url;
        BIBLIOTECASERVICE_EXCEPTION = e;
    }

    public BibliotecaService() {
        super(__getWsdlLocation(), BIBLIOTECASERVICE_QNAME);
    }

    public BibliotecaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Biblioteca
     */
    @WebEndpoint(name = "BibliotecaPort")
    public Biblioteca getBibliotecaPort() {
        return super.getPort(new QName("http://atividade4.server.soap.pos.pos.ifpb.edu.br/", "BibliotecaPort"), Biblioteca.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Biblioteca
     */
    @WebEndpoint(name = "BibliotecaPort")
    public Biblioteca getBibliotecaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atividade4.server.soap.pos.pos.ifpb.edu.br/", "BibliotecaPort"), Biblioteca.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOTECASERVICE_EXCEPTION!= null) {
            throw BIBLIOTECASERVICE_EXCEPTION;
        }
        return BIBLIOTECASERVICE_WSDL_LOCATION;
    }

}
