
package br.edu.ifpb.pos.passagem;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicePassagem", targetNamespace = "http://passagem.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePassagem {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarPassagem", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.AtualizarPassagem")
    @ResponseWrapper(localName = "atualizarPassagemResponse", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.AtualizarPassagemResponse")
    public void atualizarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "encontrarPassagem", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.EncontrarPassagem")
    @ResponseWrapper(localName = "encontrarPassagemResponse", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.EncontrarPassagemResponse")
    public void encontrarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.passagem.Passagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTodasPassagem", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.ListarTodasPassagem")
    @ResponseWrapper(localName = "listarTodasPassagemResponse", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.ListarTodasPassagemResponse")
    public List<Passagem> listarTodasPassagem();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarPassagem", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.SalvarPassagem")
    @ResponseWrapper(localName = "salvarPassagemResponse", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.SalvarPassagemResponse")
    public void salvarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removerPassagem", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.RemoverPassagem")
    @ResponseWrapper(localName = "removerPassagemResponse", targetNamespace = "http://passagem.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.passagem.RemoverPassagemResponse")
    public void removerPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
