
package br.edu.ifpb.pos.reservaHotel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceReservaHotel", targetNamespace = "http://hotel.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceReservaHotel {


    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.reservaHotel.ReservaHotel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTodasReservaHotel", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.ListarTodasReservaHotel")
    @ResponseWrapper(localName = "listarTodasReservaHotelResponse", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.ListarTodasReservaHotelResponse")
    public List<ReservaHotel> listarTodasReservaHotel();

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.ifpb.pos.reservaHotel.ReservaHotel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarReservaHotel", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.EncontrarReservaHotel")
    @ResponseWrapper(localName = "encontrarReservaHotelResponse", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.EncontrarReservaHotelResponse")
    public ReservaHotel encontrarReservaHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarReservaHotel", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.AtualizarReservaHotel")
    @ResponseWrapper(localName = "atualizarReservaHotelResponse", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.AtualizarReservaHotelResponse")
    public void atualizarReservaHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservaHotel arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removerReservaHotel", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.RemoverReservaHotel")
    @ResponseWrapper(localName = "removerReservaHotelResponse", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.RemoverReservaHotelResponse")
    public void removerReservaHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservaHotel arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarReservaHotel", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.SalvarReservaHotel")
    @ResponseWrapper(localName = "salvarReservaHotelResponse", targetNamespace = "http://hotel.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.reservaHotel.SalvarReservaHotelResponse")
    public void salvarReservaHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservaHotel arg0);

}
