package chat;


/**
* chat/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatCorba.idl
* Quinta-feira, 22 de Junho de 2017 11h00min27s GFT
*/

public interface ChatOperations 
{
  String chamar ();
  void shutdown ();
} // interface ChatOperations
