
package br.edu.ifpb.pos.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceClienteService", targetNamespace = "http://cliente.server.todeferias.soap.pos.pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-todeferias-server-cliente/ServiceClienteService?wsdl")
public class ServiceClienteService
    extends Service
{

    private final static URL SERVICECLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECLIENTESERVICE_EXCEPTION;
    private final static QName SERVICECLIENTESERVICE_QNAME = new QName("http://cliente.server.todeferias.soap.pos.pos.ifpb.edu.br/", "ServiceClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-todeferias-server-cliente/ServiceClienteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECLIENTESERVICE_WSDL_LOCATION = url;
        SERVICECLIENTESERVICE_EXCEPTION = e;
    }

    public ServiceClienteService() {
        super(__getWsdlLocation(), SERVICECLIENTESERVICE_QNAME);
    }

    public ServiceClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServiceCliente
     */
    @WebEndpoint(name = "ServiceClientePort")
    public ServiceCliente getServiceClientePort() {
        return super.getPort(new QName("http://cliente.server.todeferias.soap.pos.pos.ifpb.edu.br/", "ServiceClientePort"), ServiceCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceCliente
     */
    @WebEndpoint(name = "ServiceClientePort")
    public ServiceCliente getServiceClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cliente.server.todeferias.soap.pos.pos.ifpb.edu.br/", "ServiceClientePort"), ServiceCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECLIENTESERVICE_EXCEPTION!= null) {
            throw SERVICECLIENTESERVICE_EXCEPTION;
        }
        return SERVICECLIENTESERVICE_WSDL_LOCATION;
    }

}
